/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package serverhas

import org.junit.jupiter.api.Assertions.assertTrue
import kotlin.test.Test

class AppTest {
    @Test fun appHasAGreeting() {
        assertTrue(true)
    }
}
